<x-layouts.mitra title="Direktori Talenta Alumni">
    <div class="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-6"><div><p class="text-xs font-semibold uppercase tracking-wider text-blue-600">Talent Pool</p><h1 class="mt-1 text-2xl font-bold text-slate-900">Direktori Talenta Alumni</h1><p class="mt-1 text-sm text-slate-500">Temukan kandidat berdasarkan keahlian tanpa melihat kontak pribadi.</p></div><a href="{{ route('mitra.interview-requests.index') }}" class="text-sm font-semibold text-blue-600">Permintaan Saya</a></div>
    <form class="mb-6 flex gap-2"><input name="cari" value="{{ request('cari') }}" class="flex-1 rounded-lg border-slate-200 text-sm" placeholder="Cari nama, jurusan, atau keahlian"><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Cari</button></form>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        @forelse($alumni as $item)
            <article class="bg-white border border-slate-200 rounded-xl p-5"><div class="flex items-start justify-between gap-3"><div><h2 class="font-semibold text-slate-900">{{ $item->nama }}</h2><p class="text-xs text-slate-500 mt-1">{{ $item->jurusan }} · Lulus {{ $item->tahun_lulus }}</p></div><span class="text-[11px] rounded-full bg-emerald-50 text-emerald-700 px-2 py-1">Tersedia</span></div><p class="mt-4 text-sm font-medium text-blue-700">{{ $item->headline ?: 'Profil profesional alumni' }}</p><p class="mt-2 text-sm text-slate-600 line-clamp-3">{{ $item->ringkasan ?: 'Alumni belum menambahkan ringkasan profil.' }}</p><p class="mt-3 text-xs text-slate-500">{{ $item->keahlian ?: 'Keahlian belum diisi' }}</p><div class="mt-5 border-t border-slate-100 pt-4">@if(in_array($item->id, $requestedIds))<span class="text-xs font-semibold text-slate-500">Permintaan sudah dikirim</span>@else<form method="POST" action="{{ route('mitra.talent-pool.request', $item) }}" class="space-y-2">@csrf<textarea name="message" rows="2" class="w-full rounded-lg border-slate-200 text-xs" placeholder="Pesan untuk alumni (opsional)"></textarea><button class="w-full rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white hover:bg-blue-700">Ajukan Permintaan Wawancara</button></form>@endif</div></article>
        @empty <div class="md:col-span-2 xl:col-span-3 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Belum ada profil talenta yang tersedia.</div> @endforelse
    </div>
    <div class="mt-6">{{ $alumni->links() }}</div>
</x-layouts.mitra>
